"""Guards the generated model reference in docs/reference/model/.

The reference is generated, so the risk is not that it goes stale --
`make check-generated` covers that -- but that it is generated *wrong*:
links that do not resolve, sections silently dropped, or a page that claims
cardinality the schema does not model.

Two of the bugs these caught were in the generator, not the content:

- a ternary bound to a whole string concatenation, so every property without
  an `inverse` silently lost its entire Definition section
- a "defined on" lookup that returned the hierarchy root for every inherited
  property, misattributing DefinedProduct's slots to What_Subject
"""
import json
import re
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
MODEL = REPO / 'docs' / 'reference' / 'model'
CLASSES = MODEL / 'classes'
PROPS = MODEL / 'properties'
SCHEMA = REPO / 'src' / 'dfc_business_linkml_v2_0.yaml'

sys.path.insert(0, str(REPO))
from scripts.generate_model_reference import (  # noqa: E402
    all_slots_of, defining_class, parents_of, predicate_for, slug,
)

LINK = re.compile(r'\]\((?!https?:|#)([^)#]+)')


def schema() -> dict:
    with open(SCHEMA, encoding='utf-8') as fh:
        return yaml.safe_load(fh)


def test_reference_exists():
    assert MODEL.is_dir(), (
        'docs/reference/model/ is generated by scripts/generate_model_reference.py; '
        'run make generate'
    )


def test_every_class_has_a_page():
    classes = schema()['classes']
    missing = [c for c in classes if not (MODEL / 'classes' / f'{slug(c)}.md').is_file()]
    assert not missing, f'missing class pages: {missing[:5]}'


def test_every_property_has_a_page():
    slots = schema()['slots']
    missing = [s for s in slots if not (MODEL / 'properties' / f'{slug(s)}.md').is_file()]
    assert not missing, f'missing property pages: {missing[:5]}'


def test_every_vocabulary_has_a_page():
    enums = schema()['enums']
    missing = [e for e in enums if not (MODEL / f'{slug(e)}.md').is_file()]
    assert not missing, f'missing vocabulary pages: {missing}'


def test_no_stray_pages():
    """A page for something the schema no longer has is stale output."""
    classes = set(schema()['classes'])
    slots = set(schema()['slots'])
    enums = set(schema()['enums'])

    for f in (MODEL / 'classes').glob('*.md'):
        if f.stem != 'index':
            assert f.stem in classes, f'orphan class page: {f.name}'
    for f in (MODEL / 'properties').glob('*.md'):
        if f.stem != 'index':
            assert f.stem in slots, f'orphan property page: {f.name}'
    for f in MODEL.glob('*.md'):
        if f.stem != 'index':
            assert f.stem in enums, f'orphan vocabulary page: {f.name}'


def test_all_internal_links_resolve():
    broken = []
    for page in sorted(MODEL.rglob('*.md')):
        for target in LINK.findall(page.read_text(encoding='utf-8')):
            resolved = (page.parent / target).resolve()
            if not resolved.exists():
                broken.append(f'{page.relative_to(MODEL)} -> {target}')
    assert not broken, 'broken links:\n' + '\n'.join(broken[:15])


@pytest.mark.parametrize('name', ['has_unit', 'supplied_by', 'value', 'image'])
def test_property_pages_have_a_definition(name):
    """Regression: a ternary swallowed the section when inverse was absent."""
    text = (MODEL / 'properties' / f'{slug(name)}.md').read_text(encoding='utf-8')
    assert '## Definition' in text, f'{name} lost its Definition section'
    assert '**Predicate**' in text
    assert '**Range**' in text


def test_predicate_matches_the_connector():
    """The reference's predicate must be the one the connectors actually emit."""
    slots = schema()['slots']
    ts = (REPO / 'typescript-connector' / 'src' / 'models' / 'QuantitativeValue.ts')
    if not ts.is_file():
        pytest.skip('TypeScript connector not generated')
    text = ts.read_text(encoding='utf-8')
    for slot_name, slot in slots.items():
        if slot_name in ('has_unit', 'value'):
            assert f'"{predicate_for(slot_name, slot)}"' in text, (
                f'predicate for {slot_name} disagrees with the connector'
            )


def test_property_pages_state_cardinality_matching_the_schema():
    """Every property page states a cardinality, and it matches the schema.

    This used to be the inverse: it asserted the docs claimed *no* cardinality,
    because the schema modelled none. The converter now records it, so the risk
    has inverted -- a page that stays silent, or that contradicts the schema, is
    the defect worth failing on.
    """
    sch = schema()
    slots = sch['slots']
    offenders = []
    for name, slot in slots.items():
        # Deprecated properties get a stub page with no Definition section --
        # they are excluded from the tables so a reader finds what to use.
        if (slot or {}).get('deprecated'):
            continue
        page = PROPS / f'{name}.md'
        if not page.is_file():
            continue
        text = page.read_text(encoding='utf-8')
        match = re.search(r'- \*\*Cardinality\*\*: (.+)', text)
        if not match:
            offenders.append(f'{name}: no cardinality line')
            continue
        line = match.group(1)
        capped_everywhere = slot.get('maximum_cardinality') == 1
        restricted_on = sorted(
            c for c, d in sch['classes'].items()
            if name in (d.get('slot_usage') or {})
        )
        if capped_everywhere:
            # Also class-restricted in two cases; the global cap is the stronger
            # claim, so short-circuit rather than testing both.
            if '**Single-valued**' not in line:
                offenders.append(f'{name}: capped at 1 everywhere but page says otherwise')
        elif restricted_on:
            if '**Single-valued on' not in line:
                offenders.append(f'{name}: restricted on {restricted_on} but page says otherwise')
        else:
            # Neither capped nor restricted: the page must still say which way
            # it falls, and must not imply the ontology settled it.
            if not ('**Collection**' in line or '**Scalar**' in line):
                offenders.append(f'{name}: page states no collection/scalar claim: {line[:80]}')
    assert not offenders, (
        'reference cardinality disagrees with the schema:\n'
        + '\n'.join(offenders[:15])
    )


def test_collection_pages_do_not_claim_ontology_authority():
    """A collection claim must name its real source.

    The ontology states no `owl:maxCardinality` at all, so a page may never say
    a property is a collection *because the ontology says so*.
    """
    offenders = []
    for page in PROPS.rglob('*.md'):
        text = page.read_text(encoding='utf-8')
        for line in text.splitlines():
            if '**Collection**' not in line:
                continue
            if 'ontology states no upper bound' not in line or 'curated' not in line:
                offenders.append(f'{page.relative_to(MODEL)}: {line.strip()[:110]}')
    assert not offenders, (
        'collection cardinality presented as ontology fact:\n'
        + '\n'.join(offenders[:10])
    )


def test_defined_on_credits_the_nearest_ancestor():
    """Regression: this reported the root for every inherited property."""
    s = schema()
    classes, slots = s['classes'], s['slots']
    # DefinedProduct declares these; What_Subject is further up the chain.
    for slot in ('image', 'brand'):
        if slot not in slots:
            continue
        owner = defining_class('SuppliedProduct', slot, classes, slots)
        assert owner == 'DefinedProduct', (
            f'{slot} attributed to {owner}, expected DefinedProduct'
        )


def test_hierarchy_is_root_first():
    s = schema()
    assert parents_of('SuppliedProduct', s['classes']) == [
        'What_Subject', 'DefinedProduct', 'SuppliedProduct',
    ]


def test_all_slots_includes_inherited():
    s = schema()
    props = all_slots_of('SuppliedProduct', s['classes'], s['slots'])
    assert 'supplied_by' in props, 'own slot missing'
    assert 'image' in props, 'inherited slot missing'
    assert len(props) == len(set(props)), 'duplicate properties'


def test_vocabulary_pages_list_bundled_concepts():
    """Enums have no permissible_values; the list comes from the bundled SKOS."""
    for name in schema()['enums']:
        text = (MODEL / f'{slug(name)}.md').read_text(encoding='utf-8')
        assert '## Concepts' in text, f'{name} has no concept list'
        assert 'not embedded in the schema' in text, (
            f'{name} should say where the values come from'
        )


def test_vocabulary_concept_count_matches_bundled_data():
    from scripts.generate_model_reference import VOCAB_FILES, read_vocab
    for name, file_name in VOCAB_FILES.items():
        concepts = read_vocab(file_name)
        if not concepts:
            continue
        text = (MODEL / f'{slug(name)}.md').read_text(encoding='utf-8')
        m = re.search(r'## Concepts \((\d+)\)', text)
        assert m, f'{name} has no concept count'
        assert int(m.group(1)) == len(concepts), (
            f'{name}: page claims {m.group(1)} concepts, bundled data has {len(concepts)}'
        )
