"""Guards the packagist publishing surface for the PHP connector.

packagist.org only reads composer.json from the repository root and has no
documented support for a subdirectory manifest, so this repo carries two:

  composer.json                 packagist manifest, generated, repo-relative
                                autoload and an archive.exclude deny-list
  php-connector/composer.json   development manifest, generated, carries
                                require-dev for the test suite

Both are generated by scripts/generate_php_connector.py, so they cannot drift
by hand. These tests pin the properties packagist and Composer actually rely
on, which the generator alone would not catch: a wrong autoload path ships a
package that installs and then fatals on first use, and a bad archive
exclude-list ships the TypeScript and Ruby connectors to every PHP consumer.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
ROOT_MANIFEST = REPO / 'composer.json'
DEV_MANIFEST = REPO / 'php-connector' / 'composer.json'

PACKAGE_NAME = 'siol-data/linkml-connector'
PHP_NAMESPACE = 'DataFoodConsortium\\Connector\\'

# Top-level entries that make up the PHP package as packagist serves it.
PHP_PACKAGE_PATHS = ('php-connector/src',)


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def _archive_excludes(manifest: dict) -> list[str]:
    return list((manifest.get('archive') or {}).get('exclude') or [])


def test_manifests_exist():
    assert ROOT_MANIFEST.is_file(), (
        'packagist requires composer.json in the repository root; it is '
        'generated by scripts/generate_php_connector.py'
    )
    assert DEV_MANIFEST.is_file()


def test_manifests_are_valid_json():
    for path in (ROOT_MANIFEST, DEV_MANIFEST):
        try:
            _load(path)
        except json.JSONDecodeError as exc:
            pytest.fail(f'{path} is not valid JSON: {exc}')


def test_composer_validate_passes():
    """`composer validate` is the same check packagist applies."""
    if not _composer_available():
        pytest.skip('composer not installed')
    r = subprocess.run(
        ['composer', 'validate', '--no-check-all', '--no-check-publish', '--no-check-lock'],
        cwd=REPO, capture_output=True, text=True,
    )
    assert r.returncode == 0, f'composer validate failed:\n{r.stdout}{r.stderr}'


def _composer_available() -> bool:
    return subprocess.run(['which', 'composer'],
                          capture_output=True).returncode == 0


@pytest.mark.parametrize('path', [ROOT_MANIFEST, DEV_MANIFEST])
def test_package_name_is_the_publish_identity(path: Path):
    # packagist vendor names are permanent once claimed, and the jsr scope is
    # @siol-data, so the PHP package must use the same identity.
    assert _load(path)['name'] == PACKAGE_NAME


@pytest.mark.parametrize('path', [ROOT_MANIFEST, DEV_MANIFEST])
def test_connectors_are_mit(path: Path):
    # The LinkML codebase is AGPLv3; the generated connectors are MIT. See the
    # header in the root LICENSE.
    assert _load(path)['license'] == 'MIT'


def test_root_manifest_omits_version():
    # packagist derives the version from the git tag; a hardcoded version
    # field would be ignored at best and misleading at worst.
    assert 'version' not in _load(ROOT_MANIFEST)


def test_root_autoload_path_resolves():
    """The autoload target must exist, or every consumer fatals on first use."""
    psr4 = _load(ROOT_MANIFEST)['autoload']['psr-4']
    assert PHP_NAMESPACE in psr4, f'expected {PHP_NAMESPACE!r} in {psr4}'
    target = REPO / psr4[PHP_NAMESPACE]
    assert target.is_dir(), f'autoload target missing: {psr4[PHP_NAMESPACE]}'
    # Spot-check that the namespace is real, not just a directory.
    assert (target / 'Connector.php').is_file(), 'Connector.php missing from autoload target'


def test_dev_autoload_path_resolves():
    psr4 = _load(DEV_MANIFEST)['autoload']['psr-4']
    target = REPO / 'php-connector' / psr4[PHP_NAMESPACE]
    assert target.is_dir(), f'autoload target missing: {psr4[PHP_NAMESPACE]}'


def test_root_and_dev_require_php_agree():
    assert _load(ROOT_MANIFEST)['require'] == _load(DEV_MANIFEST)['require']


def test_dev_manifest_carries_test_dependencies():
    # The root manifest is publish-only; the dev manifest is what CI installs.
    assert 'phpunit/phpunit' in _load(DEV_MANIFEST).get('require-dev', {})


def test_archive_excludes_other_connectors():
    """PHP consumers must not download the TypeScript and Ruby packages."""
    excludes = _archive_excludes(_load(ROOT_MANIFEST))
    for other in ('/typescript-connector', '/ruby-gem', '/src', '/scripts',
                  '/tests', '/config', '/docs', '/.github'):
        assert other in excludes, f'{other} missing from archive.exclude'


def test_archive_excludes_the_agpl_codebase_license():
    """The root LICENSE is AGPLv3; shipping it inside an MIT package misstates it.

    The MIT notice for this package ships as php-connector/LICENSE.
    """
    assert '/LICENSE' in _archive_excludes(_load(ROOT_MANIFEST))


def test_archive_keeps_the_php_package():
    """The exclude-list must not remove what the autoloader needs."""
    excludes = _archive_excludes(_load(ROOT_MANIFEST))
    for keep in PHP_PACKAGE_PATHS:
        assert f'/{keep}' not in excludes, f'{keep} is excluded but autoloaded'
    assert '/php-connector' not in excludes, 'php-connector must not be excluded'


def test_archive_excludes_are_absolute_paths():
    """Relative patterns would silently match nothing."""
    for pattern in _archive_excludes(_load(ROOT_MANIFEST)):
        if pattern.endswith('_pycache_*') or '*' in pattern:
            continue
        assert pattern.startswith('/'), f'archive.exclude entry must be repo-absolute: {pattern!r}'


def test_connectors_ship_mit_license():
    """Each connector needs its own MIT LICENSE for the licence to travel.

    The Ruby gem's LICENSE is generated (and the gem is wiped and rebuilt on
    every `make generate`), so this also catches a generator regression that
    reintroduces the old AGPL stub.
    """
    for connector in ('typescript-connector', 'ruby-gem', 'php-connector'):
        path = REPO / connector / 'LICENSE'
        assert path.is_file(), f'{path} missing'
        text = path.read_text(encoding='utf-8')
        assert 'MIT License' in text, f'{path} is not MIT'
        assert 'AGPL' not in text, f'{path} still carries AGPL text'
        assert 'Permission is hereby granted' in text, f'{path} is not the full MIT text'


def test_ruby_gemspec_declares_mit_and_ships_license():
    """The gemspec is generated too; MIT is worthless if it is not packaged."""
    gemspec = (REPO / 'ruby-gem' / 'dfc-linkml-connector.gemspec').read_text(encoding='utf-8')
    assert 'spec.license       = "MIT"' in gemspec, 'gemspec licence is not MIT'
    assert 'AGPL' not in gemspec, 'gemspec still declares AGPL'
    assert '["LICENSE", "README.md"]' in gemspec.replace('\n', ' ').replace('\\', ''), (
        'gemspec spec.files must include LICENSE and README.md'
    )


def test_codebase_license_is_agpl():
    text = (REPO / 'LICENSE').read_text(encoding='utf-8')
    assert 'GNU AFFERO GENERAL PUBLIC LICENSE' in text
    # The header must name the split, or readers cannot tell which side the
    # connectors fall on.
    assert 'MIT' in text, 'root LICENSE should state the connectors are MIT'


def test_generated_manifests_are_current():
    """`make check-generated` is the real guard; this localises the failure.

    Compares against a fresh generator run rather than `git diff`, because a
    legitimate uncommitted edit to either manifest would otherwise be reported
    as staleness.
    """
    import tempfile

    from scripts.generate_php_connector import (
        generate_composer_json,
        generate_root_composer_json,
        parse_schema,
    )

    schema = parse_schema(REPO / 'src' / 'dfc_business_linkml_v2_0.yaml')
    with tempfile.TemporaryDirectory() as tmp:
        fresh_root = Path(tmp) / 'composer.json'
        fresh_root.write_text(generate_root_composer_json(schema), encoding='utf-8')
        fresh_dev = Path(tmp) / 'dev-composer.json'
        fresh_dev.write_text(generate_composer_json(schema), encoding='utf-8')

        for path, fresh in ((ROOT_MANIFEST, fresh_root), (DEV_MANIFEST, fresh_dev)):
            assert path.read_text(encoding='utf-8') == fresh.read_text(encoding='utf-8'), (
                f'{path.relative_to(REPO)} is stale; run make generate'
            )


def test_root_manifest_excludes_are_synced_with_the_tree():
    """A new top-level directory must be a deliberate choice, not an accident.

    The deny-list is intentional rather than an allow-list so that adding an
    unrelated directory cannot silently produce an empty package, but every
    current top-level entry should be accounted for one way or the other.
    """
    excludes = set(_archive_excludes(_load(ROOT_MANIFEST)))
    top_level = {
        p.name for p in REPO.iterdir()
        if p.is_dir() and not p.name.startswith('.') and p.name != 'node_modules'
        and '__pycache__' not in p.name
    }
    # Directories that are part of the PHP package as packagist serves it.
    shipped = {PHP_PACKAGE_PATHS[0].split('/')[0]}
    unaccounted = top_level - shipped - {
        e.lstrip('/') for e in excludes if '/' not in e.lstrip('/')
    }
    assert not unaccounted, (
        'top-level directories neither shipped nor excluded from the packagist '
        f'dist: {sorted(unaccounted)} -- add them to archive.exclude'
    )


def test_archive_exclude_covers_every_excluded_path():
    """Guard against a typo in a path that silently excludes nothing."""
    excludes = _archive_excludes(_load(ROOT_MANIFEST))
    for pattern in excludes:
        if '*' in pattern:
            continue
        assert (REPO / pattern.lstrip('/')).exists(), (
            f'archive.exclude lists {pattern!r} but no such path exists'
        )


def test_archive_exclude_omits_the_php_package_root():
    """php-connector must ship whole: autoload, LICENSE, README."""
    excludes = _archive_excludes(_load(ROOT_MANIFEST))
    for pattern in excludes:
        stripped = pattern.lstrip('/')
        # A parent of the shipped path would remove it.
        assert not PHP_PACKAGE_PATHS[0].startswith(stripped + '/'), (
            f'archive.exclude {pattern!r} would remove the autoloaded package'
        )
