"""Guards the docs entry point, the guides, and the generated API reference.

The model reference is covered by test_model_reference.py. This covers the
hand-written surface around it and the API page, which is generated by
*parsing the connector sources* -- so the risk there is a parser that
silently under-reports, which is exactly what happened once (it dropped every
`async` method and every `get` accessor, understating the TypeScript API by a
third).
"""
import re
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / 'docs'
API = DOCS / 'reference' / 'api'
GUIDES = DOCS / 'guides'

sys.path.insert(0, str(REPO))
from scripts.generate_api_reference import (  # noqa: E402
    OPERATIONS, TS_CONNECTOR, parse_php, parse_ruby, parse_ts,
)

ENTRY = DOCS / 'index.md'
GUIDE_PAGES = [
    'index.md',
    'build-a-catalog.md',
    'load-and-validate.md',
    'handle-identifiers.md',
    'work-offline.md',
]

LINK = re.compile(r'\]\((?!https?:|mailto:|#)([^)#]+)')


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8')


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def test_entry_point_exists():
    assert ENTRY.is_file(), 'docs/index.md is the entry point; docs/ has no door'


def test_conformance_report_exists():
    """Phase 4 acceptance: the fixtures x connectors matrix, auto-updated.

    Generated by scripts/generate_conformance_report.py and wired into the
    reference step, so --check covers it and it cannot drift from the suite.
    """
    page = DOCS / 'conformance.md'
    assert page.is_file(), 'docs/conformance.md is missing'
    text = page.read_text(encoding='utf-8')
    assert 'Do not edit' in text, 'the page should say it is generated'
    # Every fixture and every connector has to appear, or the table silently
    # omits coverage rather than reporting it missing.
    fixtures = sorted((REPO / 'tests' / 'conformance' / 'valid').glob('*.jsonld'))
    assert fixtures, 'no conformance fixtures found'
    for fixture in fixtures:
        assert f'## {fixture.stem}' in text, f'no section for {fixture.stem}'
    for display in ('TypeScript', 'Ruby', 'PHP'):
        assert display in text, f'{display} missing from the conformance report'


def test_conformance_report_covers_every_fixture_and_connector():
    """The report must have a cell for every fixture/connector/property pair.

    Counted rather than eyeballed: a table that silently drops a row reads as
    coverage it does not have.
    """
    text = (DOCS / 'conformance.md').read_text(encoding='utf-8')
    fixtures = sorted((REPO / 'tests' / 'conformance' / 'valid').glob('*.jsonld'))
    # Two properties (import, round-trip) per connector per fixture.
    expected_rows = len(fixtures) * 3
    per_fixture_rows = [
        ln for ln in text.splitlines()
        if ln.startswith('| ') and ('npx jsr add' in ln or 'gem install' in ln
                                    or 'composer require' in ln)
        and not ln.startswith('| Connector')
        and 'Install |' not in ln
    ]
    # Fixture tables: 3 connectors each, plus 3 summary rows.
    assert len(per_fixture_rows) == expected_rows + 3, (
        f'expected {expected_rows} fixture cells + 3 summary rows, '
        f'found {len(per_fixture_rows)}'
    )


def test_conformance_report_says_what_it_does_not_cover():
    """Conformance is a floor. The page must not imply it validates DFC."""
    text = (DOCS / 'conformance.md').read_text(encoding='utf-8')
    assert 'What this does not cover' in text
    assert 'validation.md' in text, 'should defer to the validation concept page'
    # No negative fixtures exist yet, so nothing may be asserted as rejected.
    assert 'no connector is asserted to reject anything yet' in text


def test_entry_point_links_every_top_level_section():
    text = read(ENTRY)
    for target in (
        'getting-started/hello-dfc.md',
        'guides/index.md',
        'concepts/index.md',
        'reference/model/index.md',
        'reference/api/index.md',
        'migration-guide.md',
        'architecture.md',
        'generation.md',
        'sdk-contract.md',
        'licensing.md',
    ):
        assert f']({target})' in text, f'docs/index.md does not link {target}'


def test_entry_point_documents_all_three_installs():
    text = read(ENTRY)
    assert 'npx jsr add @siol-data/linkml-connector' in text
    assert 'gem install dfc-linkml-connector' in text
    assert 'composer require siol-data/dfc-connector' in text


def test_entry_point_hello_matches_reality():
    """The @context position differs per connector, so the note must exist.

    TypeScript and Ruby emit @context first, PHP last. The entry point shows
    one document; without the note a reader diffing against PHP output would
    think something was wrong.
    """
    text = read(ENTRY)
    assert 'key order' in text, (
        'the entry point should note that JSON key order differs by connector'
    )


# ---------------------------------------------------------------------------
# Guides
# ---------------------------------------------------------------------------

def test_guides_exist():
    missing = [p for p in GUIDE_PAGES if not (GUIDES / p).is_file()]
    assert not missing, f'missing guides: {missing}'


def test_guides_index_lists_every_guide():
    index = read(GUIDES / 'index.md')
    for p in GUIDE_PAGES:
        if p == 'index.md':
            continue
        assert f']({p})' in index, f'guides/index.md does not link {p}'


def test_build_a_catalog_uses_the_real_price_shape():
    """Regression guard.

    The first draft of this guide hung a Price off SuppliedProduct. There is
    no such slot: has_price lives on Offer, OrderLine, PaymentMethod, and
    Transaction. TypeScript accepted `carrots.price = ...` without complaint
    and dropped the value on export, so the example looked fine and produced
    no price at all.
    """
    text = read(GUIDES / 'build-a-catalog.md')
    assert 'createOffer' in text, 'the guide must build an Offer'
    assert 'createCatalogItem' in text, 'the bridge node is part of the shape'
    # It must warn against the mistake explicitly, since the connector
    # accepts the bad assignment without complaint.
    assert 'does not raise' in text, (
        'the guide should warn that a non-existent slot is silently ignored'
    )
    assert 'has_price' in text, 'the guide should say where has_price lives'


def test_guides_link_into_concepts_not_the_other_way():
    """Guides are recipes, concepts are explanation; the link points that way."""
    for p in GUIDE_PAGES:
        if p == 'index.md':
            continue
        text = read(GUIDES / p)
        assert '../concepts/' in text, f'{p} does not link into docs/concepts/'


# ---------------------------------------------------------------------------
# API reference
# ---------------------------------------------------------------------------

def test_api_reference_exists():
    for p in ('index.md', 'typescript.md', 'ruby.md', 'php.md'):
        assert (API / p).is_file(), f'docs/reference/api/{p} missing'


def test_api_pages_match_the_parsers():
    """Every method the parsers find must be on the page, and vice versa."""
    cases = [
        ('typescript', parse_ts(TS_CONNECTOR)[0]),
        ('ruby', parse_ruby(REPO / 'ruby-gem' / 'lib' / 'core' / 'connector.rb')[0]),
        ('php', parse_php(REPO / 'php-connector' / 'src' / 'Connector.php')[0]),
    ]
    for slug, methods in cases:
        text = read(API / f'{slug}.md')
        for m in methods:
            assert f'`{m}()`' in text, f'{slug}.md omits parsed method {m}'


def test_ts_parser_finds_async_and_accessors():
    """Regression: the first parser dropped both, understating the API.

    TypeScript's connector has 3 async methods and 6 `get` accessors. If
    either count collapses to zero, the parser has regressed.
    """
    methods, _factories, accessors = parse_ts(TS_CONNECTOR)
    async_methods = [m for m in methods if m.startswith(('getContext', 'load'))]
    assert len(async_methods) >= 3, f'async methods missing: {methods}'
    assert len(accessors) >= 6, f'get accessors missing: {accessors}'
    assert 'contextUrl' in accessors
    for acc in ('facet', 'measure', 'product_type'):
        assert acc in accessors, f'{acc} accessor missing'


def test_ruby_parser_finds_its_real_accessors():
    """Ruby exposes some state via attr_reader and some via def.

    `facet`/`measure`/`product_type` are defs (they lazy-load), so they land
    in the method list. Only the plain state is attr_reader.
    """
    methods, accessors = parse_ruby(
        REPO / 'ruby-gem' / 'lib' / 'core' / 'connector.rb'
    )
    for acc in ('ontology_version', 'taxonomy_version', 'vocab_loader'):
        assert acc in accessors, f'ruby attr_reader {acc} missing'
    for meth in ('facet', 'measure', 'product_type'):
        assert meth in methods, f'ruby def {meth} missing'


def test_operations_table_covers_the_parsed_surface():
    """Every operation named for a language must be callable there.

    Accessors count as callable: `contextUrl` is a TS getter, not a method,
    so the availability set has to include accessors or this reports a false
    failure.
    """
    ts_methods, _f, ts_acc = parse_ts(TS_CONNECTOR)
    rb_methods, rb_acc = parse_ruby(
        REPO / 'ruby-gem' / 'lib' / 'core' / 'connector.rb'
    )
    php_methods, _pf, php_acc = parse_php(
        REPO / 'php-connector' / 'src' / 'Connector.php'
    )
    available = {
        1: set(ts_methods) | set(ts_acc),
        2: set(rb_methods) | set(rb_acc),
        3: set(php_methods) | set(php_acc),
    }
    for op in OPERATIONS:
        for col, names in available.items():
            bare = op[col][0]
            if bare is None:
                continue
            assert bare in names, (
                f'operations table claims {op[0]!r} exists as {bare!r} '
                f'but the connector has no such member'
            )


def test_api_page_does_not_claim_ruby_has_factories():
    text = read(API / 'ruby.md')
    assert 'no factories' in text.lower() or 'Constructing objects' in text
    index = read(API / 'index.md')
    assert '| 0 |' in index, 'the index should show Ruby has 0 factories'


def test_facade_counts_match_schema_class_count():
    """Every DFC class should have a factory in TS and PHP, and none in Ruby."""
    classes = yaml.safe_load(
        (REPO / 'src' / 'dfc_business_linkml_v2_0.yaml').read_text(encoding='utf-8')
    )['classes']
    n = len(classes)
    ts_factories = len(parse_ts(TS_CONNECTOR)[1])
    php_factories = len(parse_php(REPO / 'php-connector' / 'src' / 'Connector.php')[1])
    assert ts_factories == n, f'TS has {ts_factories} factories for {n} classes'
    assert php_factories == n, f'PHP has {php_factories} factories for {n} classes'


# ---------------------------------------------------------------------------
# Links
# ---------------------------------------------------------------------------

def test_all_links_in_docs_resolve():
    broken = []
    for page in sorted(DOCS.rglob('*.md')):
        for target in LINK.findall(read(page)):
            if not (page.parent / target).resolve().exists():
                broken.append(f'{page.relative_to(DOCS)} -> {target}')
    assert not broken, 'broken links:\n' + '\n'.join(broken[:20])


def test_licensing_page_states_the_split():
    text = read(DOCS / 'licensing.md')
    assert 'AGPLv3' in text
    assert 'MIT' in text
    for conn in ('typescript-connector', 'ruby-gem', 'php-connector'):
        assert conn in text, f'licensing.md omits {conn}'
