# frozen_string_literal: true

class Price < ApplicationRecord
  self.table_name = 'prices'
  
  # Class from DFC Business Ontology: #Price
  # Root class for this hierarchy
  # Associations

  # Enum: Facet
  enum facet: {abeille: abeille, aberdeenshire: aberdeenshire, africa: africa, afrique: afrique, 
    agriculture_biologique: agriculture_biologique, agriculture_biologique_eu: agriculture_biologique_eu, algae: algae, algue: algue, allemagne: allemagne, 
    allglight: allglight, allgation_nutritionnelle: allgation_nutritionnelle, allgation_sant: allgation_sant, allgations_nutritionnelles_et_de_sant: allgations_nutritionnelles_et_de_sant, amrique_du_nord: amrique_du_nord, 
    amrique_du_sud: amrique_du_sud, angleterre: angleterre, animal: animal, appellation_dorigine_contrle: appellation_dorigine_contrle, appellation_dorigine_protge: appellation_dorigine_protge, 
    asia: asia, asie: asie, australia: australia, australie: australie, autre_allgation: autre_allgation, 
    auvergne_rhne_alpes: auvergne_rhne_alpes, ayrshire: ayrshire, bacteria: bacteria, bactrie: bactrie, bedfordshire: bedfordshire, 
    bee: bee, belgique: belgique, belgium: belgium, berkshire: berkshire, bio_coherence: bio_coherence, 
    biodynamic_label: biodynamic_label, bleu_blanc_coeur: bleu_blanc_coeur, bourgogne_franche_comt: bourgogne_franche_comt, brebis: brebis, bretagne: bretagne, 
    bristol: bristol, brittany: brittany, buckinghamshire: buckinghamshire, buf: buf, bulb: bulb, 
    bulbe: bulbe, bull: bull, bulls_body: bulls_body, caille: caille, cambridgeshire: cambridgeshire, 
    centre_val_de_loire: centre_val_de_loire, certification: certification, champignon: champignon, cheshire: cheshire, chicken: chicken, 
    chickens_body: chickens_body, chvre: chvre, cire_dabeille: cire_dabeille, cochon: cochon, container_information: container_information, 
    contains_nutrient_or_other_substance: contains_nutrient_or_other_substance, contient_nutriment_ou_autre_substance: contient_nutriment_ou_autre_substance, coq: coq, cornwall: cornwall, corse: corse, 
    corsica: corsica, county_durham: county_durham, cow: cow, cow_milk: cow_milk, cows_body: cows_body, 
    cumbria: cumbria, demeter: demeter, derbyshire: derbyshire, devon: devon, dorset: dorset, 
    dumfries_and_galloway: dumfries_and_galloway, dunbartonshire: dunbartonshire, eu_organic_farming: eu_organic_farming, east_midlands: east_midlands, east_riding_of_yorkshire: east_riding_of_yorkshire, 
    east_sussex: east_sussex, east_of_england: east_of_england, eastern_scotland: eastern_scotland, eau: eau, ecosse: ecosse, 
    edinburgh: edinburgh, elu_produit_de_lanne: elu_produit_de_lanne, energy_free: energy_free, energy_reduced: energy_reduced, england: england, 
    enrichi_en_nutriment: enrichi_en_nutriment, espagne: espagne, essex: essex, ethical_label: ethical_label, europe: europe, 
    ewe: ewe, ewes_body: ewes_body, faible_teneur_en_graisses_satures: faible_teneur_en_graisses_satures, faible_teneur_en_matire_grasse: faible_teneur_en_matire_grasse, faible_teneur_en_sucres: faible_teneur_en_sucres, 
    faible_valeur_nergtique: faible_valeur_nergtique, fairtrade_max_haavelar: fairtrade_max_haavelar, fat_free: fat_free, feuille: feuille, fleur: fleur, 
    flower: flower, forest_stewardship_council: forest_stewardship_council, fort_durable_fsc: fort_durable_fsc, france: france, fruit: fruit, 
    funghi: funghi, germany: germany, glossaire_des_facettes_de_produit: glossaire_des_facettes_de_produit, gloucestershire: gloucestershire, gluten_free: gluten_free, 
    goat: goat, goat_milk: goat_milk, goats_body: goats_body, graine: graine, grand_est: grand_est, 
    greater_manchester: greater_manchester, hampshire: hampshire, haute_valeur_environnementale: haute_valeur_environnementale, hauts_de_france: hauts_de_france, health_claim: health_claim, 
    hen: hen, hens_body: hens_body, hens_egg: hens_egg, herefordshire: herefordshire, hertfordshire: hertfordshire, 
    high_environnemental_value: high_environnemental_value, high_fibre: high_fibre, high_monounsaturated_fat: high_monounsaturated_fat, high_omega_3_fatty_acids: high_omega_3_fatty_acids, high_polyunsaturated_fat: high_polyunsaturated_fat, 
    high_protein: high_protein, high_unsaturated_fat: high_unsaturated_fat, high_vitamins_andor_minerals: high_vitamins_andor_minerals, highlands_and_islands: highlands_and_islands, honey: honey, 
    ile_de_france: ile_de_france, increased_nutrient: increased_nutrient, indication_gographique_de_provenance: indication_gographique_de_provenance, irlande_du_nord: irlande_du_nord, isle_of_wight: isle_of_wight, 
    italie: italie, italy: italy, kent: kent, label_rouge: label_rouge, label_biodynamie: label_biodynamie, 
    label_biologique: label_biologique, label_inconnu: label_inconnu, label_local: label_local, label_marketing: label_marketing, label_thique: label_thique, 
    lait_de_brebis: lait_de_brebis, lait_de_vache: lait_de_vache, lanarkshire: lanarkshire, lancashire: lancashire, leaf: leaf, 
    leicestershire: leicestershire, lightlite: lightlite, lincolnshire: lincolnshire, local_label: local_label, london: london, 
    lothian: lothian, lowlight: lowlight, low_energy: low_energy, low_fat: low_fat, low_saturated_fat: low_saturated_fat, 
    low_sodiumsalt: low_sodiumsalt, low_sugars: low_sugars, marine_stewardship_council: marine_stewardship_council, marketing_label: marketing_label, merseyside: merseyside, 
    miel: miel, milk_fed: milk_fed, mineral: mineral, minral: minral, mouton: mouton, 
    multi_territorial_origin: multi_territorial_origin, multiorigin: multiorigin, natural_origin: natural_origin, naturallynatural: naturallynatural, nature_et_progrs: nature_et_progrs, 
    netherlands: netherlands, new_zealand: new_zealand, no_added_sodiumsalt: no_added_sodiumsalt, norfolk: norfolk, normandie: normandie, 
    normandy: normandy, north_america: north_america, north_east_england: north_east_england, north_east_scotland: north_east_scotland, north_west_england: north_west_england, 
    north_yorkshire: north_yorkshire, northamptonshire: northamptonshire, northern_ireland: northern_ireland, northumberland: northumberland, nottinghamshire: nottinghamshire, 
    nourri_au_lait: nourri_au_lait, nouvelle_aquitaine: nouvelle_aquitaine, nouvelle_zlande: nouvelle_zlande, nutrition_and_health_claims: nutrition_and_health_claims, nutritional_claim: nutritional_claim, 
    ocanie: ocanie, occitania: occitania, occitanie: occitanie, oceania: oceania, organic_label: organic_label, 
    origine_gographique: origine_gographique, origine_multiple: origine_multiple, origine_territorial_multiple: origine_territorial_multiple, origine_territoriale_inconnue: origine_territoriale_inconnue, other_claim: other_claim, 
    oxfordshire: oxfordshire, package: package, part_of_origin: part_of_origin, part_or_product_of_animal: part_or_product_of_animal, part_or_product_of_plant: part_or_product_of_plant, 
    partie_de_brebis: partie_de_brebis, partie_de_chvre: partie_de_chvre, partie_de_coq: partie_de_coq, partie_de_mouton: partie_de_mouton, partie_de_poule: partie_de_poule, 
    partie_de_vache: partie_de_vache, partie_dorigine: partie_dorigine, partie_dorigine_inconnue: partie_dorigine_inconnue, partie_du_boeuf: partie_du_boeuf, partie_du_cochon: partie_du_cochon, 
    partie_du_poulet: partie_du_poulet, partie_ou_produit_dun_animal: partie_ou_produit_dun_animal, partie_ou_produit_dune_plante: partie_ou_produit_dune_plante, pauvre_en_sodiumsel: pauvre_en_sodiumsel, pays_bas: pays_bas, 
    pays_de_galles: pays_de_galles, pays_de_la_loire: pays_de_la_loire, paysans_de_nature: paysans_de_nature, pche_durable_msc: pche_durable_msc, pig: pig, 
    pigs_body: pigs_body, plant: plant, plante: plante, plante_entire: plante_entire, pollen: pollen, 
    portugal: portugal, poule: poule, poulet: poulet, product_glossary_facets: product_glossary_facets, product_of_the_year: product_of_the_year, 
    propolis: propolis, protected_geographical_status: protected_geographical_status, provence_alpes_cte_dazur: provence_alpes_cte_dazur, quail: quail, quails_egg: quails_egg, 
    racine: racine, rainforest_alliance: rainforest_alliance, rduit_en_nutriment: rduit_en_nutriment, reconnu_saveur_de_lanne: reconnu_saveur_de_lanne, reduced_nutrient: reduced_nutrient, 
    renfrewshire: renfrewshire, republic_of_ireland: republic_of_ireland, riche_en_acide_gras_omga_3: riche_en_acide_gras_omga_3, riche_en_fibres: riche_en_fibres, riche_en_graisses_insatures: riche_en_graisses_insatures, 
    riche_en_graisses_monoinsatures: riche_en_graisses_monoinsatures, riche_en_graisses_polyinsatures: riche_en_graisses_polyinsatures, riche_en_protines: riche_en_protines, riche_en_vitamines_etou_de_minraux: riche_en_vitamines_etou_de_minraux, rooster: rooster, 
    roosters_body: roosters_body, root: root, royaume_uni: royaume_uni, rpublique_dirlande: rpublique_dirlande, rutland: rutland, 
    sans_apport_nergtique: sans_apport_nergtique, sans_gluten: sans_gluten, sans_graisses_satures: sans_graisses_satures, sans_matires_grasses: sans_matires_grasses, sans_sodium_ou_sans_sel: sans_sodium_ou_sans_sel, 
    sans_sodiumsel_ajout: sans_sodiumsel_ajout, sans_sucres_ajouts: sans_sucres_ajouts, saturated_fat_free: saturated_fat_free, scotland: scotland, scottish_borders: scottish_borders, 
    seed: seed, sheep: sheep, sheep_milk: sheep_milk, sheeps_body: sheeps_body, shropshire: shropshire, 
    sodium_free_or_salt_free: sodium_free_or_salt_free, somerset: somerset, source_dacide_gras_omga_3: source_dacide_gras_omga_3, source_de_fibres: source_de_fibres, source_de_protine: source_de_protine, 
    source_de_vitamines_etou_de_minraux: source_de_vitamines_etou_de_minraux, source_dorigine_inconnue: source_dorigine_inconnue, source_naturelle_dorigine: source_naturelle_dorigine, source_of_fibre: source_of_fibre, source_of_omega_3_fatty_acids: source_of_omega_3_fatty_acids, 
    source_of_protein: source_of_protein, source_of_vitamins_andor_minerals: source_of_vitamins_andor_minerals, south_america: south_america, south_east_england: south_east_england, south_west_england: south_west_england, 
    south_western_scotland: south_western_scotland, south_yorkshire: south_yorkshire, spain: spain, staffordshire: staffordshire, statut_gographique_protg: statut_gographique_protg, 
    stem: stem, suffolk: suffolk, sugars_free: sugars_free, suisse: suisse, surrey: surrey, 
    switzerland: switzerland, taste_of_the_year: taste_of_the_year, territorial_origin: territorial_origin, tige: tige, trs_pauvre_en_sodiumsel: trs_pauvre_en_sodiumsel, 
    tuber: tuber, tubercule: tubercule, tyne__wear: tyne__wear, united_kingdom: united_kingdom, unknown_label: unknown_label, 
    unknown_nature_origin: unknown_nature_origin, unknown_part_origin: unknown_part_origin, unknown_territorial_origin: unknown_territorial_origin, vache: vache, valeur_nergtique_rduite: valeur_nergtique_rduite, 
    vegan: vegan, vegetarian: vegetarian, venim_dabeille: venim_dabeille, venom: venom, very_low_sodiumsalt: very_low_sodiumsalt, 
    vgtarien: vgtarien, wales: wales, warwickshire: warwickshire, water: water, wax: wax, 
    west_midlands: west_midlands, west_midlands_conurbation: west_midlands_conurbation, west_sussex: west_sussex, west_yorkshire: west_yorkshire, whole_plant: whole_plant, 
    wiltshire: wiltshire, with_no_added_sugars: with_no_added_sugars, worcestershire: worcestershire, yorkshire_and_the_humber: yorkshire_and_the_humber, le_de_france: le_de_france, 
    uf_de_caille: uf_de_caille, uf_de_poule: uf_de_poule}

  # Enum: ProductType
  enum product_type: {fromage_frais_de_brebis: fromage_frais_de_brebis, patate_douce: patate_douce, pied_bleu: pied_bleu, pied_de_mouton: pied_de_mouton, 
    pourpier: pourpier, purslane: purslane, venison: venison, viande_de_cerf: viande_de_cerf, abricot: abricot, 
    agneau: agneau, ail: ail, aillet: aillet, alcoholic_beverage: alcoholic_beverage, almond: almond, 
    amande: amande, aneth: aneth, aperitif: aperitif, apples: apples, apricot: apricot, 
    apritif: apritif, aromate: aromate, aromate_sec: aromate_sec, artichaut: artichaut, artichoke: artichoke, 
    asparagus: asparagus, asperges: asperges, aubergine: aubergine, autre_fromage: autre_fromage, autre_lait: autre_lait, 
    autre_produit_laitier: autre_produit_laitier, bakery: bakery, basil: basil, basilic: basilic, bay_laurel: bay_laurel, 
    bean: bean, beans: beans, beef: beef, beer: beer, beetroot: beetroot, 
    berry: berry, betterave_rouge: betterave_rouge, beurre: beurre, bire: bire, biscuit: biscuit, 
    blackberry: blackberry, blackcurrant: blackcurrant, blettes: blettes, blueberry: blueberry, bluefoot_mushroom: bluefoot_mushroom, 
    boisson: boisson, boisson_alcoolise: boisson_alcoolise, boisson_non_alcoolise: boisson_non_alcoolise, bottled_fruit: bottled_fruit, bottled_vegetable: bottled_vegetable, 
    boulangerie: boulangerie, bread: bread, broccoli_cabbage: broccoli_cabbage, brussels_sprouts: brussels_sprouts, butter: butter, 
    butternut: butternut, button_mushroom: button_mushroom, cabbage: cabbage, caille: caille, canard: canard, 
    canned_fruit: canned_fruit, canned_goods: canned_goods, canned_vegetable: canned_vegetable, carotte: carotte, carrot: carrot, 
    cassis: cassis, cauliflower: cauliflower, celeriac: celeriac, celery_branch: celery_branch, cerfeuil: cerfeuil, 
    cerise: cerise, chalote: chalote, champignon: champignon, champignon_de_paris: champignon_de_paris, chanterelle: chanterelle, 
    chanterelle_mushroom: chanterelle_mushroom, charcuterie: charcuterie, chard: chard, cherry: cherry, cherry_tomato: cherry_tomato, 
    chervil: chervil, chestnut: chestnut, chicken: chicken, chicore: chicore, chicory: chicory, 
    chilli_pepper: chilli_pepper, chinese_cabbage: chinese_cabbage, chive: chive, chou: chou, chou_brocoli: chou_brocoli, 
    chou_chinois: chou_chinois, chou_fleur: chou_fleur, chou_fris: chou_fris, chou_kale: chou_kale, chou_lisse: chou_lisse, 
    chou_pomm: chou_pomm, chou_rave: chou_rave, chou_romanesco: chou_romanesco, chou_rouge: chou_rouge, choux_de_bruxelles: choux_de_bruxelles, 
    ciboulette: ciboulette, cider: cider, cidre: cidre, citron: citron, clementine: clementine, 
    cleri_branche: cleri_branche, cleri_rave: cleri_rave, clmentine: clmentine, cluster_tomato: cluster_tomato, coing: coing, 
    concombre: concombre, confectionery: confectionery, confiserie: confiserie, confiture: confiture, cooked_meat: cooked_meat, 
    coquillage: coquillage, coriander: coriander, coriandre: coriandre, corn_saladlambs_lettuce: corn_saladlambs_lettuce, cosmetic: cosmetic, 
    cosmtique: cosmtique, coulemelle: coulemelle, courge: courge, courgette: courgette, cow_dairy_product: cow_dairy_product, 
    cpes: cpes, crale: crale, cream_cheese: cream_cheese, crepe_and_galette: crepe_and_galette, cress: cress, 
    cresson: cresson, crme_frache: crme_frache, crpe_et_galette: crpe_et_galette, crustacs: crustacs, cucumber: cucumber, 
    curly_kale: curly_kale, currant: currant, dairy_dessert: dairy_dessert, dairy_product: dairy_product, dandelion: dandelion, 
    deaths_trumpet: deaths_trumpet, delicatessen: delicatessen, dessert_lact: dessert_lact, dessert_lact_de_brebis: dessert_lact_de_brebis, dessert_lact_de_chvre: dessert_lact_de_chvre, 
    digestif: digestif, digestive: digestive, dill: dill, dinde: dinde, dried_fruit: dried_fruit, 
    dried_goods: dried_goods, dried_herb: dried_herb, dried_vegetable: dried_vegetable, drink: drink, duck: duck, 
    egg: egg, eggplant: eggplant, endive: endive, escargots: escargots, estragon: estragon, 
    farine: farine, fennel: fennel, fenouil: fenouil, ferment: ferment, festive_poultry: festive_poultry, 
    fifth_range_vegetable: fifth_range_vegetable, fig: fig, figue: figue, fish: fish, fishery_product: fishery_product, 
    flake: flake, flavored_yogurt: flavored_yogurt, fleur: fleur, flocon: flocon, flour: flour, 
    flower: flower, fourth_range_vegetable: fourth_range_vegetable, fraise: fraise, framboise: framboise, fresh_cheese: fresh_cheese, 
    fresh_cream: fresh_cream, fresh_meat: fresh_meat, fromage_affin: fromage_affin, fromage_affin_de_brebis: fromage_affin_de_brebis, fromage_blanc: fromage_blanc, 
    fromage_de_chvre_affin: fromage_de_chvre_affin, fromage_frais: fromage_frais, fromage_frais_de_chvre: fromage_frais_de_chvre, frozen: frozen, frozen_fruit: frozen_fruit, 
    frozen_meal: frozen_meal, frozen_meat: frozen_meat, frozen_vegetable: frozen_vegetable, fruit: fruit, fruit__coque: fruit__coque, 
    fruit_en_bocal: fruit_en_bocal, fruit_en_compote: fruit_en_compote, fruit_en_conserve: fruit_en_conserve, fruit_in_compote: fruit_in_compote, fruit_juice: fruit_juice, 
    fruit_non_local: fruit_non_local, fruit_sec: fruit_sec, fruit_surgel: fruit_surgel, fruit_transform: fruit_transform, fruits: fruits, 
    garlic: garlic, girolle: girolle, girolle_mushroom: girolle_mushroom, goat_dairy_dessert: goat_dairy_dessert, goat_dairy_product: goat_dairy_product, 
    goat_flavored_yogurt: goat_flavored_yogurt, goat_fresh_cheese: goat_fresh_cheese, goat_mature_cheese: goat_mature_cheese, goat_milk: goat_milk, goat_natural_yogurt: goat_natural_yogurt, 
    goat_sweet_yogurt: goat_sweet_yogurt, goat_yogurt_on_a_bed_of_fruit: goat_yogurt_on_a_bed_of_fruit, goat_yogurt_with_fruits: goat_yogurt_with_fruits, goose: goose, gooseberry: gooseberry, 
    grain: grain, graine: graine, grape: grape, green_garlic: green_garlic, grilling_meat: grilling_meat, 
    groseille: groseille, groseille__maquereau: groseille__maquereau, guinea_fowl: guinea_fowl, haricot: haricot, haricots: haricots, 
    hazelnut: hazelnut, herb: herb, hierloom_squash: hierloom_squash, hierloom_tomato: hierloom_tomato, honey: honey, 
    huile: huile, inedible: inedible, jam: jam, jerusalem_artichoke: jerusalem_artichoke, jus_de_fruits: jus_de_fruits, 
    kale: kale, kiwi: kiwi, kohlrabi: kohlrabi, lactaire: lactaire, lait: lait, 
    lait_de_brebis: lait_de_brebis, lait_de_chvre: lait_de_chvre, laitue: laitue, lamb: lamb, lapin: lapin, 
    laurier: laurier, leek: leek, lemon: lemon, lemonade: lemonade, lentilles: lentilles, 
    lentils: lentils, lettuce: lettuce, lgume: lgume, lgume_de_cinquime_gamme: lgume_de_cinquime_gamme, lgume_de_quatrime_gamme: lgume_de_quatrime_gamme, 
    lgume_en_bocal: lgume_en_bocal, lgume_en_conserve: lgume_en_conserve, lgume_non_local: lgume_non_local, lgume_sec: lgume_sec, lgume_surgel: lgume_surgel, 
    lgume_transform: lgume_transform, limonade: limonade, local_grocery_store: local_grocery_store, mandarin: mandarin, mandarine: mandarine, 
    marron: marron, mature_cheese: mature_cheese, mche: mche, meat_product: meat_product, medlar: medlar, 
    melon: melon, menthe: menthe, mesclun: mesclun, miel: miel, milk: milk, 
    milky_mushroom: milky_mushroom, mint: mint, mlange_de_salades: mlange_de_salades, morel: morel, morille: morille, 
    mousseron: mousseron, mre: mre, mushroom: mushroom, myrtille: myrtille, natural_yogurt: natural_yogurt, 
    navet: navet, nectarine: nectarine, nfle: nfle, noisette: noisette, noix: noix, 
    non_alimentaire: non_alimentaire, non_local_fruit: non_local_fruit, non_local_vegetable: non_local_vegetable, nut: nut, oie: oie, 
    oignon: oignon, oil: oil, onion: onion, orange: orange, other_cheese: other_cheese, 
    other_dairy_product: other_dairy_product, other_milk: other_milk, oyster_mushroom: oyster_mushroom, pain: pain, panais: panais, 
    parasol_mushroom: parasol_mushroom, parsley: parsley, parsnip: parsnip, pasta: pasta, pastry: pastry, 
    pattypan_squash: pattypan_squash, pche: pche, peach: peach, pear: pear, peas: peas, 
    pepper: pepper, persil: persil, petit_fruit: petit_fruit, picerie_locale: picerie_locale, picerie_sale: picerie_sale, 
    picerie_sucre: picerie_sucre, pie_pastry: pie_pastry, pigeon: pigeon, piment: piment, pinards: pinards, 
    pintade: pintade, pissenlit: pissenlit, plant: plant, plante: plante, plat_cuisin: plat_cuisin, 
    plat_surgel: plat_surgel, pleurote: pleurote, plum: plum, poire: poire, poireau: poireau, 
    pois: pois, poisson: poisson, poivron: poivron, pomme: pomme, pomme_de_terre: pomme_de_terre, 
    porc: porc, porcini: porcini, pork: pork, potato: potato, potimarron: potimarron, 
    potiron: potiron, poulet: poulet, poultry: poultry, processed_fruit: processed_fruit, processed_vegetable: processed_vegetable, 
    produit_carn: produit_carn, produit_de_la_pche: produit_de_la_pche, produit_laitier: produit_laitier, produit_laitier_de_brebis: produit_laitier_de_brebis, produit_laitier_de_chvre: produit_laitier_de_chvre, 
    produit_laitier_de_vache: produit_laitier_de_vache, produits_sec: produits_sec, prune: prune, pruneau: pruneau, pte__tarte: pte__tarte, 
    ptes: ptes, ptisserie: ptisserie, ptisson: ptisson, pulse: pulse, pumpkin: pumpkin, 
    quail: quail, quince: quince, quinoa: quinoa, rabbit: rabbit, radis: radis, 
    radish: radish, raisin: raisin, raspberry: raspberry, ready_meal: ready_meal, red_cabbage: red_cabbage, 
    rhubarb: rhubarb, rhubarbe: rhubarbe, rice: rice, riz: riz, rocket: rocket, 
    romanesco_cauliflower: romanesco_cauliflower, romarin: romarin, roquette: roquette, rosemary: rosemary, round_tomato: round_tomato, 
    rutabaga: rutabaga, sage: sage, salad: salad, salad_mix: salad_mix, salade: salade, 
    salaison: salaison, salsifis: salsifis, salsify: salsify, salt: salt, salting: salting, 
    sauge: sauge, savory_groceries: savory_groceries, savoy_cabbage: savoy_cabbage, seashell: seashell, seed: seed, 
    sel: sel, semolina: semolina, semoule: semoule, shallot: shallot, sheep_dairy_dessert: sheep_dairy_dessert, 
    sheep_dairy_product: sheep_dairy_product, sheep_flavored_yogurt: sheep_flavored_yogurt, sheep_fresh_cheese: sheep_fresh_cheese, sheep_mature_cheese: sheep_mature_cheese, sheep_milk: sheep_milk, 
    sheep_natural_yogurt: sheep_natural_yogurt, sheep_sweet_yogurt: sheep_sweet_yogurt, sheep_yogurt_on_a_bed_of_fruit: sheep_yogurt_on_a_bed_of_fruit, sheep_yogurt_with_fruits: sheep_yogurt_with_fruits, sheepfoot_mushroom: sheepfoot_mushroom, 
    shellfish: shellfish, simmering_meat: simmering_meat, smooth_cabbage: smooth_cabbage, smoothie: smoothie, snack: snack, 
    snails: snails, soft_drink: soft_drink, soup: soup, soupe: soupe, spinach: spinach, 
    squash: squash, strawberry: strawberry, surgel: surgel, sweet_groceries: sweet_groceries, sweet_yogurt: sweet_yogurt, 
    tarragon: tarragon, thym: thym, thyme: thyme, tomate: tomate, tomate_ancienne: tomate_ancienne, 
    tomate_cerise: tomate_cerise, tomate_en_grappe: tomate_en_grappe, tomate_ronde: tomate_ronde, tomato: tomato, topinambour: topinambour, 
    trompette_de_la_mort: trompette_de_la_mort, truffe: truffe, truffle: truffle, turkey: turkey, turnip: turnip, 
    uchiki_kuri_squash: uchiki_kuri_squash, uf: uf, varit_ancienne_de_courge: varit_ancienne_de_courge, veal: veal, veau: veau, 
    vegetable: vegetable, viande__griller: viande__griller, viande__mijoter: viande__mijoter, viande_bovine: viande_bovine, viande_cuite: viande_cuite, 
    viande_frache: viande_frache, viande_surgele: viande_surgele, viennoiserie: viennoiserie, vin: vin, volaille: volaille, 
    volaille_festive: volaille_festive, walnut: walnut, wine: wine, yam: yam, yaourt_aromatis: yaourt_aromatis, 
    yaourt_aux_fruits: yaourt_aux_fruits, yaourt_de_brebis_aromatis: yaourt_de_brebis_aromatis, yaourt_de_brebis_aux_fruits: yaourt_de_brebis_aux_fruits, yaourt_de_brebis_nature: yaourt_de_brebis_nature, yaourt_de_brebis_sur_lit_de_fruits: yaourt_de_brebis_sur_lit_de_fruits, 
    yaourt_de_chvre_aromatis: yaourt_de_chvre_aromatis, yaourt_de_chvre_aux_fruits: yaourt_de_chvre_aux_fruits, yaourt_de_chvre_sur_lit_de_fruits: yaourt_de_chvre_sur_lit_de_fruits, yaourt_nature: yaourt_nature, yaourt_nature_de_chvre: yaourt_nature_de_chvre, 
    yaourt_sucr: yaourt_sucr, yaourt_sucr_de_brebis: yaourt_sucr_de_brebis, yaourt_sucr_de_chvre: yaourt_sucr_de_chvre, yaourt_sur_lit_de_fruits: yaourt_sur_lit_de_fruits, yogurt_on_a_bed_of_fruit: yogurt_on_a_bed_of_fruit, 
    yogurt_with_fruits: yogurt_with_fruits}

  # Enum: Measure
  enum measure: {4_pack: 4_pack, 6_pack: 6_pack, acide_folique: acide_folique, allergen_dimension: allergen_dimension, 
    amidon: amidon, anhydride_sulfureux_et_sulfites_en_concentration_de_plus_de_10mgkg_ou_10_mgl_exprims_en_so2: anhydride_sulfureux_et_sulfites_en_concentration_de_plus_de_10mgkg_ou_10_mgl_exprims_en_so2, arachides: arachides, calcium: calcium, carbohydrates: carbohydrates, 
    celeriac: celeriac, cereals_containing_gluten: cereals_containing_gluten, chloride: chloride, cholesterol: cholesterol, cholestrol: cholestrol, 
    chrome: chrome, chromium: chromium, copper: copper, crales_contenant_du_gluten: crales_contenant_du_gluten, crustaceans: crustaceans, 
    crustacs: crustacs, currency_unit: currency_unit, depth: depth, dimension: dimension, dimension_allergne: dimension_allergne, 
    dimension_nutritionnelle: dimension_nutritionnelle, dimension_physique: dimension_physique, dimension_score_de_labellisation: dimension_score_de_labellisation, dollar_us: dollar_us, eco_score: eco_score, 
    eggs: eggs, fat: fat, fer: fer, fibre: fibre, fluoride: fluoride, 
    folic_acid: folic_acid, fruits__coque: fruits__coque, glossaire_mesure_produit: glossaire_mesure_produit, graines_de_ssame: graines_de_ssame, graisse: graisse, 
    graisse_monosature: graisse_monosature, graisse_poly_insature: graisse_poly_insature, graisse_sature: graisse_sature, graisse_trans: graisse_trans, hauteur: hauteur, 
    height: height, iodine: iodine, iron: iron, labelling_dimension: labelling_dimension, lait_et_produits__base_de_lactose: lait_et_produits__base_de_lactose, 
    largeur: largeur, lupin: lupin, lupine: lupine, magnesium: magnesium, magnsium: magnsium, 
    manganese: manganese, manganse: manganse, milk_and_lactose_based_products: milk_and_lactose_based_products, molluscs: molluscs, mollusques: mollusques, 
    monosaturated_fat: monosaturated_fat, moutarde: moutarde, mustard: mustard, nutri_score: nutri_score, nutrient_dimension: nutrient_dimension, 
    nuts: nuts, oeufs: oeufs, peanuts: peanuts, phosphore: phosphore, phosphorus: phosphorus, 
    physical_dimension: physical_dimension, planet_score: planet_score, poids: poids, poissons: poissons, poly_unsaturated_fat: poly_unsaturated_fat, 
    potassium: potassium, product_measure_glossary_: product_measure_glossary_, profondeur: profondeur, protein: protein, protine: protine, 
    quantity_unit: quantity_unit, salt: salt, saturated_fat: saturated_fat, sel: sel, selenium: selenium, 
    sesame_seeds: sesame_seeds, slnium: slnium, sodium: sodium, soja: soja, soy: soy, 
    starch: starch, sucres: sucres, sugars: sugars, sulfur_dioxide_and_sulphites_in_a_concentration_of_more_than_10mgkg_or_10mgl_expressed_as_so2: sulfur_dioxide_and_sulphites_in_a_concentration_of_more_than_10mgkg_or_10mgl_expressed_as_so2, transfat: transfat, 
    us_dollar: us_dollar, unit: unit, unit_de_devise_montaire: unit_de_devise_montaire, unit_de_quantit: unit_de_quantit, units: units, 
    vitamin_a: vitamin_a, vitamin_b12: vitamin_b12, vitamin_b6: vitamin_b6, vitamin_c: vitamin_c, vitamin_d: vitamin_d, 
    vitamin_e: vitamin_e, vitamin_k: vitamin_k, vitamine_a: vitamine_a, vitamine_b12: vitamine_b12, vitamine_b6: vitamine_b6, 
    vitamine_c: vitamine_c, vitamine_d: vitamine_d, vitamine_e: vitamine_e, vitamine_k: vitamine_k, volume: volume, 
    weight: weight, width: width, zinc: zinc, australian_dollar: australian_dollar, bac: bac, 
    bag: bag, baril: baril, barquette: barquette, basket: basket, beer_crate: beer_crate, 
    bocal: bocal, bote: bote, bote_de_conserve: bote_de_conserve, botte: botte, bottle: bottle, 
    bouteille: bouteille, box: box, bucket: bucket, bunch: bunch, bundle: bundle, 
    cagette: cagette, can: can, canadian_dollar: canadian_dollar, canette: canette, carton: carton, 
    casier__bire: casier__bire, cask: cask, centilitre: centilitre, centimetre: centimetre, centimtre: centimtre, 
    colis: colis, crate: crate, cup: cup, decilitre: decilitre, decimetre: decimetre, 
    decimtre: decimtre, demi_douzaine: demi_douzaine, dollar_australien: dollar_australien, dollar_canadien: dollar_canadien, douzaine: douzaine, 
    dozen: dozen, drum: drum, euro: euro, filet: filet, fishs: fishs, 
    ft: ft, gallon_gb: gallon_gb, gallon_uk: gallon_uk, grain_bulk: grain_bulk, grain_en_vrac: grain_en_vrac, 
    gram: gram, gramme: gramme, half_dozen: half_dozen, inch: inch, jar: jar, 
    keg: keg, kilogram: kilogram, kilogramme: kilogramme, kilometre: kilometre, kilomtre: kilomtre, 
    kit: kit, liquid_bulk: liquid_bulk, liquide_en_vrac: liquide_en_vrac, litre: litre, livre_sterling: livre_sterling, 
    lot: lot, metre: metre, milligram: milligram, milligramme: milligramme, milliliter: milliliter, 
    millilitre: millilitre, mtre: mtre, net: net, nodule_bulk: nodule_bulk, nodule_en_vrac: nodule_en_vrac, 
    once: once, ounce: ounce, pack_de_4: pack_de_4, pack_de_6: pack_de_6, package: package, 
    packet: packet, pair: pair, paire: paire, palette: palette, pallet: pallet, 
    panier: panier, percent: percent, pice: pice, piece: piece, plateau: plateau, 
    poche: poche, pot: pot, pouce: pouce, pouch: pouch, poudre_en_vrac: poudre_en_vrac, 
    pound: pound, pound_sterling: pound_sterling, pourcent: pourcent, powder_bulk: powder_bulk, punnet: punnet, 
    roll: roll, rouleau: rouleau, sac: sac, sachet: sachet, seau: seau, 
    tablet: tablet, tablette: tablette, tasse: tasse, tin: tin, tonne: tonne, 
    tonneau: tonneau, tray: tray, tub: tub, tube: tube}

  # Enum: Scope
  enum scope: {authorization_scopes: authorization_scopes, lire_les_commandes_de_lentreprise: lire_les_commandes_de_lentreprise, lire_les_donnes_de_lentreprise: lire_les_donnes_de_lentreprise, lire_les_produits_de_lentreprise: lire_les_produits_de_lentreprise, 
    primtres_dautorisation: primtres_dautorisation, read_enterprise_data: read_enterprise_data, read_enterprise_orders: read_enterprise_orders, read_enterprise_products: read_enterprise_products, write_enterprise_data: write_enterprise_data, 
    write_enterprise_orders: write_enterprise_orders, write_enterprise_products: write_enterprise_products, crire_les_commandes_de_lentreprise: crire_les_commandes_de_lentreprise, crire_les_donnes_de_lentreprise: crire_les_donnes_de_lentreprise, crire_les_produits_de_lentreprise: crire_les_produits_de_lentreprise}

  # Enum: VocabularyTerm
  enum vocabulary_term: {cancelled: cancelled, complete: complete, dfc_vocabulary: dfc_vocabulary, draft: draft, 
    fulfilled: fulfilled, fulfilmentstate: fulfilmentstate, fulfilment_state: fulfilment_state, fulfilment_status: fulfilment_status, held: held, 
    order_state: order_state, order_status: order_status, paid: paid, payment_state: payment_state, payment_status: payment_status, 
    states: states, status: status, transformation_type: transformation_type, unfulfilled: unfulfilled, unpaid: unpaid, 
    accept: accept, combine: combine, consume: consume, dropoff: dropoff, lower: lower, 
    modify: modify, move: move, pickup: pickup, produce: produce, raise: raise, 
    separate: separate, use: use}

end
