#!/usr/bin/env python3
"""Generate the conformance report page: fixtures × connectors, auto-updated.

Phase 4 of the docs plan asks for a "conformance report page (fixtures ×
connectors matrix, auto-updated)". This renders exactly what
`tests/conformance/test_conformance.py` asserts, by running the same checks, so
the page cannot drift from the suite.

Two properties per fixture per connector:

- **import**  — every node in the fixture survives import + re-export
- **round-trip** — the re-export is node-for-node and predicate-for-predicate
  identical, with the same canonical `@type` and the same normalized values

`docs/concepts/validation.md` owns the wider story about what conformance does
and does not prove; this page is the scoreboard, not the argument.

Connectors that need a runtime this machine lacks are reported as skipped
rather than silently passing, because a green table that quietly omits Ruby is
worse than an honest gap.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tests" / "cross_connector"))

from normalize import canonical_type, extract_objects, normalize_value  # noqa: E402
from runner import import_jsonld  # noqa: E402

VALID_DIR = REPO / "tests" / "conformance" / "valid"
INVALID_DIR = REPO / "tests" / "conformance" / "invalid"

# Connector name -> (display name, runtime needed, docs install command).
# The install command is what the reader has to run to get this column working,
# so the table doubles as the install matrix.
CONNECTORS = [
    ("our-typescript", "TypeScript", "node", "npx jsr add @siol-data/linkml-connector"),
    ("our-ruby", "Ruby", "ruby", "gem install dfc-linkml-connector"),
    ("our-php", "PHP", "php", "composer require siol-data/dfc-connector"),
]


@dataclass
class Result:
    status: str  # pass | fail | skip
    detail: str = ""


def load_fixture(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def check_import(fixture: dict, connector: str) -> Result:
    """Every node must survive import + re-export."""
    expected = extract_objects(fixture)
    if not expected:
        return Result("fail", "fixture has no nodes")
    try:
        actual = extract_objects(import_jsonld(connector, fixture))
    except RuntimeError as exc:
        return Result("fail", str(exc).strip().splitlines()[-1][:160])
    missing = sorted(set(expected) - set(actual))
    if missing:
        return Result("fail", f"dropped {', '.join(missing)}")
    return Result("pass")


def check_roundtrip(fixture: dict, connector: str) -> Result:
    """Re-export must match the fixture node by node and predicate by predicate."""
    expected = extract_objects(fixture)
    try:
        actual = extract_objects(import_jsonld(connector, fixture))
    except RuntimeError as exc:
        return Result("fail", str(exc).strip().splitlines()[-1][:160])

    for semantic_id, info in expected.items():
        if semantic_id not in actual:
            return Result("fail", f"lost {semantic_id}")
        other = actual[semantic_id]
        if canonical_type(other["semanticType"]) != canonical_type(info["semanticType"]):
            return Result(
                "fail",
                f"changed @type of {semantic_id}: "
                f"{info['semanticType']} -> {other['semanticType']}",
            )
        for pred, value in info["predicates"].items():
            if pred not in other["predicates"]:
                return Result("fail", f"dropped {pred} on {semantic_id}")
            if normalize_value(other["predicates"][pred]) != normalize_value(value):
                return Result("fail", f"changed {pred} on {semantic_id}")
    return Result("pass")


MARK = {
    "pass": "pass",
    "fail": "**FAIL**",
    "skip": "not run",
}


def render(fixtures: list[Path], results: dict) -> str:
    lines = [
        "# Conformance report",
        "",
        "Generated by `scripts/generate_conformance_report.py`. Do not edit — "
        "it is regenerated by `generate_all.py` and checked by "
        "`make check-generated`, so it cannot drift from the suite it reports on.",
        "",
        "Each cell is the result of running the same check "
        "`tests/conformance/test_conformance.py` runs:",
        "",
        "| Mark | Meaning |",
        "|---|---|",
        "| pass | the fixture survived the round trip unchanged |",
        "| **FAIL** | a node, `@type`, or predicate value changed |",
        "| not run | the runtime for that connector is not available here |",
        "",
    ]

    # Per-fixture tables, so a failure names the fixture rather than sitting in a
    # single grid where the reader has to hunt for which cell went red.
    for fixture in fixtures:
        lines += [
            f"## {fixture.stem}",
            "",
            f"`tests/conformance/valid/{fixture.name}` — "
            f"{len(extract_objects(load_fixture(fixture)))} node(s).",
            "",
            "| Connector | Install | Import | Round-trip | Detail |",
            "|---|---|---|---|---|",
        ]
        for name, display, _runtime, install in CONNECTORS:
            imp = results[(fixture.stem, name, "import")]
            rt = results[(fixture.stem, name, "roundtrip")]
            detail = imp.detail or rt.detail
            lines.append(
                f"| {display} | `{install}` | {MARK[imp.status]} | "
                f"{MARK[rt.status]} | {detail or '—'} |"
            )
        lines.append("")

    # Summary: one row per connector, so the overall state is one glance.
    lines += [
        "## Summary",
        "",
        "| Connector | Install | Cells passed | Failed | Not run |",
        "|---|---|---|---|---|",
    ]
    for name, display, _runtime, install in CONNECTORS:
        cells = [r for (f, n, _), r in results.items() if n == name]
        passed = sum(1 for r in cells if r.status == "pass")
        failed = sum(1 for r in cells if r.status == "fail")
        skipped = sum(1 for r in cells if r.status == "skip")
        lines.append(
            f"| {display} | `{install}` | {passed} | {failed or '0'} | "
            f"{skipped or '0'} |"
        )
    lines += [
        "",
        "## What this does not cover",
        "",
        "Conformance is a floor, not a ceiling. Passing every cell means a "
        "document survives a round trip through that connector — it does not "
        "mean the document is valid DFC. See "
        "[validation](concepts/validation.md) for the four levels of "
        "validity and which one this is, and "
        "[cardinality](concepts/cardinality.md) for the constraint data the "
        "connectors carry.",
        "",
        "`tests/conformance/invalid/` is a placeholder for negative fixtures. It "
        "is empty, so **no connector is asserted to reject anything yet**.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="docs/conformance.md")
    args = parser.parse_args(argv)

    fixtures = sorted(VALID_DIR.glob("*.jsonld"))
    if not fixtures:
        raise SystemExit(f"no fixtures in {VALID_DIR}")

    results: dict[tuple[str, str, str], Result] = {}
    for fixture in fixtures:
        data = load_fixture(fixture)
        for name, _display, runtime, _install in CONNECTORS:
            if shutil.which(runtime) is None:
                results[(fixture.stem, name, "import")] = Result(
                    "skip", f"{runtime} not available"
                )
                results[(fixture.stem, name, "roundtrip")] = Result(
                    "skip", f"{runtime} not available"
                )
                continue
            results[(fixture.stem, name, "import")] = check_import(data, name)
            results[(fixture.stem, name, "roundtrip")] = check_roundtrip(data, name)

    out = REPO / args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(fixtures, results), encoding="utf-8")

    failures = [(k, r) for k, r in results.items() if r.status == "fail"]
    skipped = [k for k, r in results.items() if r.status == "skip"]
    print(f"  conformance report -> {out.relative_to(REPO)}")
    print(
        f"  {len(results) - len(failures) - len(skipped)} passed, "
        f"{len(failures)} failed, {len(skipped)} not run"
    )
    for key, result in failures:
        print(f"    FAIL {key[0]} / {key[1]} / {key[2]}: {result.detail}")


if __name__ == "__main__":
    main()
